name: Build App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Étape pour installer les dépendances Node.js
      - name: Install NPM dependencies
        run: |
          npm install --production --unsafe-perm

      # Étape pour exécuter OWASP Dependency Check en utilisant un conteneur Docker
      - name: Run OWASP Dependency Check
        run: |
          docker run --rm -v "$(pwd):/work" owasp/dependency-check:latest --scan /work

      # Étape pour archiver les rapports de dépendances
      - name: Archive dependency check reports
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: dependency-check-report
