name: Build App

on:
    push:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: build-push
          uses: docker/build-push-action@v1
          with:
            username: ${{ secrets.proxyfit }}
            password: ${{ secrets.proxyfit }}
            registry: docker.io
            repository: proxyfit/cd
            tag_with_sha: true

        - uses: sburris/dependency-check-action@master
          with:
            Project-Name: TestApp

        - name: Archive dependency check reports
          uses: actions/upload-artifact@v1
          with:
            name: reports
            path: reports

        - uses: actions/checkout@v2
        - name: Install NPM dependencies
          run: |
            npm install --production --unsafe-perm
